### ISSUE TITLE
不知这是不是个问题

### ISSUE THREAD

**Issue by lennonover** [barretlee/blogChat#1]
小胡子哥你好
![image](https://cloud.githubusercontent.com/assets/14219399/17083400/63072564-51d2-11e6-980a-22843b42fe39.png)
在初始化的闭合状态
当用户触发 chatroom-tribes li的点击事件会激活文本输入框聚焦状态
 $('.chatroom textarea').focus();
这时就没法展开聊天窗口了
同样在收起后也有这样问题O(∩_∩)O~

**Comment by barretlee** [comment]
这个我修复了，demo 中没有同步，我的个人博客是好的。
