### ISSUE TITLE
小胡子哥，你好，我想请教几个关于websocket的问题

### ISSUE THREAD

**Issue by lagolas** [barretlee/blogChat#10]
小胡子哥，你好，我想请教几个关于websocket的问题，无奈找不到能直接联系你的方式，看到你在github提交的代码比较多，所以你应该能看到我的留言，可以加下我的qq或者微信吗，我想请教几个问题。谢谢。困扰好几天了。
qq  1113484046
微信 15152116961
谢谢谢谢

**Comment by barretlee** [comment]
你可以在这里留言：http://www.barretlee.com/message/
