### ISSUE TITLE
新消息，是否可以自动滚动到底部？

### ISSUE THREAD

**Issue by idjanbo** [barretlee/blogChat#3]
如题

**Comment by barretlee** [comment]
已经添加了。
- 如果是自己发送消息，直接滚到底部
- 如果切换私聊 tab，自动滚到底部
- 如果在群聊，发出 3-8 条消息后就会滚动到底部

**Comment by idjanbo** [comment]
额 很人性化。这个挺好玩的 ，如果在加个拖拽和调整大小就更好玩了

**Comment by barretlee** [comment]
目的是不是把这东西做的很完善，只是一个简单的聊天窗口，代码写的很散乱，满足基本需求即可。

**Comment by idjanbo** [comment]
是否还可以在浏览器tab标题中显示有新消息呢，群聊可以没有，私聊就ok

**Comment by barretlee** [comment]
博客不是一个消息站点，不打算做这种干预用户的事情。

**Comment by idjanbo** [comment]
关闭私聊banner，群聊消息回滚到了最顶端。。问题 = new 问题();

**Comment by barretlee** [comment]
你还真是测试小能手，已经修复了，稍后更新。

**Comment by idjanbo** [comment]
[得意]  跟你同岁，刚毕业，弄弄博客，准备混个工作。。
