### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yeket** [barretlee/blogChat#5]
Missing error handler on `socket`.
TypeError: Object function Object() { [native code] } has no method 'assign'

什么鬼

**Comment by barretlee** [comment]
代码中用了 Object.assign 函数，你可以升级下你的 Node 版本。

**Comment by yeket** [comment]
升级完了，还是出这。。

**Comment by barretlee** [comment]
@yeket 你更新下代码，我已经把 assign 函数删除了。

**Comment by yeket** [comment]
okay了 thx
