### ISSUE TITLE
被攻击了还是怎么的？为什么只要回复信息页面就一直刷新

### ISSUE THREAD

**Issue by hechuanhua** [barretlee/blogChat#6]
被攻击了还是怎么的？为什么只要回复信息页面就一直刷新

**Comment by barretlee** [comment]
应该是被攻击了，我想想他是怎么攻击的。现在应该好了，重启了服务。

**Comment by barretlee** [comment]
42["pm",{"msg":"hello","id":"0.3368867891840637tfst\"]:eq(\"></div><img src=aaa onerror=location.reload(true)><!--\"),[yy=\"xxx","name":"123","type":"PM"}]   

确认被攻击了。

**Comment by hechuanhua** [comment]
还在刷新啊，没看到怎么攻击的，我还以为转义了就攻击不到了，我太年轻了，2333333

**Comment by barretlee** [comment]
修复了。

**Comment by xqin** [comment]
我表示对上午的事情负责.
之前已经在[v2ex](https://v2ex.com/t/294659#r_3400249)和楼主反馈过在他修复之后,还是有bug,
但楼主选择忽略我的友情提醒, 所以上午就做了一下小测试.

---

另外你`git log`上的`attack`拼错了. 
https://github.com/barretlee/blogChat/commit/01fc2db92338c04c61d2f84bf0be7c52febeb5e1
https://github.com/barretlee/blogChat/commit/9dc7cabfaaa0335ceef068d4406fbeb2037d5ed9

**Comment by barretlee** [comment]
@xqin 我不是指责，哈哈哈，感谢反馈。
