### ISSUE TITLE
写代码写傻了吧?

### ISSUE THREAD

**Issue by xqin** [barretlee/blogChat#7]
![image](https://cloud.githubusercontent.com/assets/1265888/17136591/e51be82c-5368-11e6-83ef-bc24cf0a9c73.png)

``` javascript
if(a > 100){
    return;
}

if(a > 500){
    return;
}
```

请问这样的代码, 什么时候能执行到 `> 500` 的那个 `if` 里面?

另外 `> 100`  就 `return`, 且每条消息都进行累计, 这是要实现一个用户最多只能发送100条消息吗?

**Comment by barretlee** [comment]
两个逻辑顺序已经调整。

只允许发送 100 条，防刷，如果想继续聊天，刷新页面就行了
