### ISSUE TITLE
当在线人数超过 1000 人之后, 再次触发pong方法, 服务器js会报错的问题

### ISSUE THREAD

**Issue by xqin** [barretlee/blogChat#8]
![image](https://cloud.githubusercontent.com/assets/1265888/17163929/265192be-53f6-11e6-8c09-e4bc167f3c57.png)

![image](https://cloud.githubusercontent.com/assets/1265888/17163942/3b0824ac-53f6-11e6-9e36-299e41f635d9.png)

**Comment by barretlee** [comment]
人数超过 1k 的时候，应该直接 return 掉了吧，而且 onlineUser 我也重置为空了。socket.emit 方法不该执行...

我加了进程守护，挂了会重启。

**Comment by xqin** [comment]
你描述的是`超过1k的时候`, 我描述的是`超过1k之后`, 再次进入到`pong`这个方法,你取到的`socket`是`undefined`, 然后接下来的 `emit` 就出错了.

另外代码的bug, 不是靠 守护进程解决的, 你的代码在超过到 1000 人之后, 重置 `onlineUser` 导致所有在线用户数据丢失.

**Comment by barretlee** [comment]
嗯，我加了一个 `socket` 为空的容错。

我的系统能够承受的在线人数在 200 左右，博客同时在线人数有 50 人已经算是特别高了。所以对 `blogChat` 来说，超过 1k 本身就是异常情况，最初的想法，异常就直接重启，这样最暴力但是成本也是最低的。

代码很多逻辑都不够完善，不过这几天增加了一些安全限制，基本可以满足我的需求。
