### ISSUE TITLE
怎么我放到服务器上了，没有确认名字的界面，也一直是一个人

### ISSUE THREAD

**Issue by wody11** [barretlee/blogChat#9]
怎么弄啊

**Comment by barretlee** [comment]
控制台没有报错吧？没有人登录你的页面，当然是你自己一个人。尝试用多个浏览器打开，看看人数增加了没有.

**Comment by wody11** [comment]
没有报错，而且我本地试了也是不行的，都没有确认名字的界面，你试下 www.wodylinda.com/talk/
看下

**Comment by xqin** [comment]
@wody11  因为你网站的 80 端口并没有由 nodejs 启动的那个脚本接管.

你的这个地址是 404, `socket.io` 和客户端连接不到你的 `socket.io` 的服务器.
http://www.wodylinda.com/socket.io/?EIO=3&transport=polling&t=1469600219767-0
